"""Build the 'Knows What' (concept) BEIR dataset for the Cocina Cloud lab.

Paper alignment (arXiv:2412.20953, §4.1 & §6.2)
-----------------------------------------------
GASLITE's objective (Eq. 2) maximizes alignment between the adversarial passage
and the **centroid of the targeted query distribution** — it is corpus-agnostic
and query-count-agnostic. The "Knows What" adversary targets a *concept* (a set
of related queries) instead of one query, so a SINGLE passage (budget=1) covers
all phrasings of the topic. Per §G.6.1, the concept queries may be **synthetic
(LLM-generated)** — no real query logs needed, which fits the fictional Cocina
Cloud KB.

What this writes (extends the SAME `data/cocina` dataset used by knows-all)
--------------------------------------------------------------------------
    data/cocina/
    ├── corpus.jsonl      # legit chunks (same splitter/ids as ChromaDB)
    ├── queries.jsonl     # q1 (knows-all) + cq001..cqNN (concept queries)
    └── qrels/test.tsv    # each query -> its current top-1 legit chunk (Pgold)

    config/cover_alg/concept-cocina.yaml   # auto-generated, concept_qids filled

Run from the repo dir, in the gaslite venv:
    python build_cocina_concept.py
"""
import argparse
import json
from pathlib import Path

from sentence_transformers import SentenceTransformer, util as st_util

# Reuse the SUT-mirroring chunker from the knows-all builder.
from build_cocina_beir import load_documents, chunk_documents, EMBED_MODEL, DEFAULT_CORPUS

DEFAULT_OUT = "data/cocina"
CONCEPT_FILE = "../concept_queries_cocina.json"     # repo -> attacks/gaslite/
COVER_ALG_OUT = "config/cover_alg/concept-cocina.yaml"
KNOWS_ALL_QID = "q1"                                 # keep knows-all working too


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default=DEFAULT_CORPUS)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--concept-file", default=CONCEPT_FILE)
    ap.add_argument("--model", default=EMBED_MODEL)
    args = ap.parse_args()

    spec = json.loads(Path(args.concept_file).read_text(encoding="utf-8"))
    concept_name = spec["concept_name"]
    info = spec["info"]
    concept_queries = spec["queries"]
    print(f"Concept '{concept_name}': {len(concept_queries)} synthetic queries")

    docs = load_documents(args.corpus)
    chunks = chunk_documents(docs)
    print(f"Loaded {len(docs)} docs -> {len(chunks)} chunks")

    model = SentenceTransformer(args.model)
    chunk_texts = [c["text"] for c in chunks]
    chunk_emb = model.encode(chunk_texts, normalize_embeddings=True,
                             show_progress_bar=True, convert_to_tensor=True)

    # Assemble queries: q1 (knows-all) + cq001..  (concept).
    queries = [{"_id": KNOWS_ALL_QID, "text": concept_queries[0]}]
    concept_qids = []
    for i, q in enumerate(concept_queries, start=1):
        qid = f"cq{i:03d}"
        concept_qids.append(qid)
        queries.append({"_id": qid, "text": q})

    # Per-query gold = current top-1 legit chunk (the passage the adv must beat).
    q_emb = model.encode([q["text"] for q in queries], normalize_embeddings=True,
                         convert_to_tensor=True)
    sims = st_util.cos_sim(q_emb, chunk_emb)  # (n_queries, n_chunks)
    gold = {}
    for i, q in enumerate(queries):
        top = int(sims[i].argmax())
        gold[q["_id"]] = chunks[top]["id"]

    # --- Write BEIR files ---
    out = Path(args.out)
    (out / "qrels").mkdir(parents=True, exist_ok=True)
    with open(out / "corpus.jsonl", "w", encoding="utf-8") as f:
        for c in chunks:
            f.write(json.dumps({"_id": c["id"], "title": "", "text": c["text"]},
                               ensure_ascii=False) + "\n")
    with open(out / "queries.jsonl", "w", encoding="utf-8") as f:
        for q in queries:
            f.write(json.dumps(q, ensure_ascii=False) + "\n")
    with open(out / "qrels" / "test.tsv", "w", encoding="utf-8") as f:
        f.write("query-id\tcorpus-id\tscore\n")
        for qid, pid in gold.items():
            f.write(f"{qid}\t{pid}\t1\n")

    # --- Auto-generate the cover_alg config so concept_qids stay in sync ---
    # YAML-encode the qid list (json list is valid YAML flow sequence).
    qids_yaml = "[" + ", ".join(f"'{q}'" for q in concept_qids) + "]"
    cover_yaml = f"""# AUTO-GENERATED by build_cocina_concept.py — do not edit by hand.
# 'Knows What' concept attack for the Cocina Cloud lab (budget=1).

concept_name: {concept_name}
data_split: test          # our local 'cocina' branch ignores this; must NOT be 'gen_qs'
data_portion: 1.0

covering_algo_name: kmeans
n_clusters: 1             # budget = 1 adversarial passage (one centroid)
concept_portion_to_train: 0.5   # first 50% held-in (centroid); rest held-out (eval)

# Malicious info carried by the passage (canary URL is appended downstream by
# generate_poisoned_corpus.py). Placed as prefix per the paper's primacy effect.
toxic_passage: "{info}"

concept_qids: {qids_yaml}
"""
    Path(COVER_ALG_OUT).write_text(cover_yaml, encoding="utf-8")

    print(f"\nWrote BEIR dataset to {out.resolve()} "
          f"({len(queries)} queries, {len(chunks)} chunks)")
    print(f"Wrote cover_alg config to {Path(COVER_ALG_OUT).resolve()}")
    print(f"Held-in (train centroid): {len(concept_qids)//2} | "
          f"held-out (eval): {len(concept_qids) - len(concept_qids)//2}")


if __name__ == "__main__":
    main()
